//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    //partial关键字表示部分类,其余地方写了这个partial修饰的部分类，最后使用这个类的时候具有叠加效果
    public partial class Articles
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ReadTimes { get; set; }
        public string Tags { get; set; }
        public string SimpleInfo { get; set; }
        public string Cont { get; set; }
        public string MainPicUrl { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> PubTime { get; set; }
        public string IsPub { get; set; }
        public string ShowType { get; set; }
    }

    //定义查询类
    public class ArticlesQuery
    {
        public ArticlesQuery(){
            this.page = 1;
            this.limit = 10;
        }
        public string title {get; set;}
        public string type {get;set;}
        public int page {get; set;}
        public int limit {get;set;}
        public string tags { get; set; }
    } 
}
