//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecArticlesView
    {
        public string Title { get; set; }
        public int Id { get; set; }
        public int PosId { get; set; }
        public int Weight { get; set; }
        public Nullable<int> ReadTimes { get; set; }
        public string Tags { get; set; }
        public string SimpleInfo { get; set; }
        public string Cont { get; set; }
        public string MainPicUrl { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> PubTime { get; set; }
        public string IsPub { get; set; }
        public string ShowType { get; set; }
        public int RecId { get; set; }
    }
}
